version: "3.9"

services:
  erika:
    build: .
    image: erika:${TAG}
    container_name: erika
    network_mode: host
    pull_policy: never

networks:
  default: 
    external: true
    name: host